# Generated by Django 4.2.16 on 2024-11-12 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TodoItem',
            new_name='Item',
        ),
    ]
