# Generated by Django 4.2.16 on 2025-01-07 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_todoitem_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('goal_distance', models.IntegerField()),
                ('weekly_mileages', models.JSONField()),
                ('long_run_distances', models.JSONField()),
                ('total_distance', models.IntegerField()),
            ],
        ),
    ]
