# Generated by Django 4.2.16 on 2025-01-07 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_trainingplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingplan',
            name='total_distance',
            field=models.JSONField(),
        ),
    ]
