# Generated by Django 4.2.16 on 2025-01-07 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_trainingplan_total_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingplan',
            name='user_id',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
