# Generated by Django 4.2.16 on 2025-01-07 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_trainingplan_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingplan',
            name='title',
            field=models.CharField(default=' ', max_length=255),
            preserve_default=False,
        ),
    ]
